#### Define the stages & order of execution

stages:
  - CLUSTER-SETUP
  - OPENEBS-SETUP
  - FUNCTIONAL
  - CHAOS
  - CLEANUP

OS-3.10-EE:
  image: openebs/openshift-ci:latest
  stage: CLUSTER-SETUP
  script:     
    - chmod 755 ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/1-cluster-setup/cluster-state.sh
    - ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/1-cluster-setup/cluster-state.sh

OPENEBS-0.8.1:
  image: openebs/openshift-ci:latest
  stage: OPENEBS-SETUP
  script:
    - chmod 775 ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/2-setup/deploy-openebs.sh
    - ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/2-setup/deploy-openebs.sh
  
OPENEBS-POOL:
  image: openebs/openshift-ci:latest
  stage: OPENEBS-SETUP
  script:
    - chmod 775 ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/2-setup/create-pool.sh
    - ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/2-setup/create-pool.sh

POLICIES:
  image: openebs/openshift-ci:latest
  stage: OPENEBS-SETUP
  script:
    - chmod 775 ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/2-setup/openebs-sc
    - ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/2-setup/openebs-sc
    
.func_test_template:
  image: openebs/openshift-ci:latest
  stage: FUNCTIONAL
  parallel: 2
  when: always 

Snapshot:
  extends: .func_test_template
  script: 
    - chmod 775 ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/3-functional/UC1-snapshot/snapshot
    - ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/3-functional/UC1-snapshot/snapshot

Clone:
  extends: .func_test_template
  script: 
    - chmod 775 ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/3-functional/UC2-snapshot-clone/snapshot-clone
    - ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/3-functional/UC2-snapshot-clone/snapshot-clone

Snap-1-Rebuild:
  extends: .func_test_template
  script: 
    - chmod 775 ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/3-functional/UC3-snap-rebuild-single-rep/snap-rebuild-single-rep
    - ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/3-functional/UC3-snap-rebuild-single-rep/snap-rebuild-single-rep

Snap-2-Rebuild:
  extends: .func_test_template
  script: 
    - chmod 775 ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/3-functional/UC4-snap-rebuild-multiple-rep/snap-rebuild-multiple-rep
    - ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/3-functional/UC4-snap-rebuild-multiple-rep/snap-rebuild-multiple-rep

Clone-1-Rebuild:
  extends: .func_test_template
  script: 
    - chmod 775 ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/3-functional/UC5-clone-pre-snap-rebuild/clone-pre-rebuild
    - ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/3-functional/UC5-clone-pre-snap-rebuild/clone-pre-rebuild

Clone-2-Rebuild:
  extends: .func_test_template
  script: 
    - chmod 775 ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/3-functional/UC6-clone-during-snap-rebuild/clone-during-rebuild
    - ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/3-functional/UC6-clone-during-snap-rebuild/clone-during-rebuild

Clone-3-Rebuild:
  extends: .func_test_template
  script: 
    - chmod 775 ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/3-functional/UC7-clone-post-snap-rebuild/clone-post-rebuild
    - ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/3-functional/UC7-clone-post-snap-rebuild/clone-post-rebuild

Parent-vol-delete:
  extends: .func_test_template
  script: 
    - chmod 775 ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/3-functional/UC8-Clone-parent-vol-delete/clone-parent-vol-delete
    - ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/3-functional/UC8-Clone-parent-vol-delete/clone-parent-vol-delete

App-Upgrade:
  extends: .func_test_template
  script: 
    - chmod 775 ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/3-functional/UC9-Application-Upgrade/application-upgrade
    - ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/3-functional/UC9-Application-Upgrade/application-upgrade

App-Scaleup:
  extends: .func_test_template
  script: 
    - chmod 775 ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/3-functional/UC10-Sts-App-replica-scaleup/app-replica-scaleup
    - ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/3-functional/UC10-Sts-App-replica-scaleup/app-replica-scaleup

Storage-Scaleup:
  extends: .func_test_template
  script: 
    - chmod 775 ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/3-functional/UC11-Storage-Volume-scaleup/storage-volume-scaleup
    - ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/3-functional/UC11-Storage-Volume-scaleup/storage-volume-scaleup

Storage-Upgrade:
  extends: .func_test_template
  script: 
    - chmod 775 ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/3-functional/UC12-Storage-volume-upgrade/storage-volume-upgrade
    - ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/3-functional/UC12-Storage-volume-upgrade/storage-volume-upgrade

Vol-Distribute:
  extends: .func_test_template
  script: 
    - chmod 775 ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/3-functional/UC13-STS-Volume-Distribution/volume-distribution
    - ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/3-functional/UC13-STS-Volume-Distribution/volume-distribution

Data-Integrity:
  extends: .func_test_template
  script: 
    - chmod 775 ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/3-functional/UC14-Data-Integrity/data-integrity
    - ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/3-functional/UC14-Data-Integrity/data-integrity

Memory-Usage:
  extends: .func_test_template
  script: 
    - chmod 775 ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/3-functional/UC15-Memory-Consumption/memory-consumption
    - ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/3-functional/UC15-Memory-Consumption/memory-consumption

Volume-Capacity:
  extends: .func_test_template
  script: 
    - chmod 775 ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/3-functional/UC16-Volume-Capacity/volume-capacity
    - ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/3-functional/UC16-Volume-Capacity/volume-capacity

.chaos_test_template:
  image: openebs/openshift-ci:latest
  stage: CHAOS
  when: always
  parallel: 2

Application:
  extends: .chaos_test_template
  script: 
    - chmod 775 ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/4-chaos/UC-1-app-kill/app-kill
    - ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/4-chaos/UC-1-app-kill/app-kill

Target:
  extends: .chaos_test_template
  script: 
    - chmod 775 ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/4-chaos/UC-2-istgt-kill/istgt-kill
    - ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/4-chaos/UC-2-istgt-kill/istgt-kill

cStor-Pool:
  extends: .chaos_test_template
  script: 
    - chmod 775 ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/4-chaos/UC-3-pool-kill/pool-kill
    - ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/4-chaos/UC-3-pool-kill/pool-kill
    
Volume:
  extends: .chaos_test_template
  script: 
    - chmod 775 ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/4-chaos/UC-4-volume-kill/volume-kill
    - ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/4-chaos/UC-4-volume-kill/volume-kill

Target-n/w-Delay:
  extends: .chaos_test_template
  script: 
    - chmod 775 ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/4-chaos/UC-5-target-network-delay/target-network-delay
    - ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/4-chaos/UC-5-target-network-delay/target-network-delay

Target-n/w-Loss:
  extends: .chaos_test_template
  script: 
    - chmod 775 ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/4-chaos/UC-5-target-network-loss/target-network-loss
    - ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/4-chaos/UC-5-target-network-loss/target-network-loss

Pool-n/w-Loss:
  extends: .chaos_test_template
  script: 
    - chmod 775 ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/4-chaos/UC-6-pool-network-loss/pool-network-loss
    - ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/4-chaos/UC-6-pool-network-loss/pool-network-loss

Pool-n/w-Delay:
  extends: .chaos_test_template
  script: 
    - chmod 775 ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/4-chaos/UC-7-pool-network-delay/pool-network-delay
    - ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/4-chaos/UC-7-pool-network-delay/pool-network-delay

Volume-Manager:
  extends: .chaos_test_template
  script: 
    - chmod 775 ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/4-chaos/UC-8-zrepl-kill/zrepl-kill
    - ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/4-chaos/UC-8-zrepl-kill/zrepl-kill

Kubelet-Crash:
  extends: .chaos_test_template
  script: 
    - chmod 775 ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/4-chaos/UC-9-kubelet-down/kubelet-down
    - ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/4-chaos/UC-9-kubelet-down/kubelet-down

Node-Shutdown:
  extends: .chaos_test_template
  script: 
    - chmod 775 ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/4-chaos/UC-10-node-shutdown/node-shutdown
    - ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/4-chaos/UC-10-node-shutdown/node-shutdown

Docker-Crash:
  extends: .chaos_test_template
  script: 
    - chmod 775 ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/4-chaos/UC-11-docker-down/docker-down
    - ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/4-chaos/UC-11-docker-down/docker-down

Mem-Pressure:
  extends: .chaos_test_template
  script: 
    - chmod 775 ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/4-chaos/UC-12-memory-pressure/memory-pressure
    - ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/4-chaos/UC-12-memory-pressure/memory-pressure

CPU-Pressure:
  extends: .chaos_test_template
  script: 
    - chmod 775 ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/4-chaos/UC-13-cpu-pressure/cpu-pressure
    - ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/4-chaos/UC-13-cpu-pressure/cpu-pressure

Node-Drain:
  extends: .chaos_test_template
  script: 
    - chmod 775 ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/4-chaos/UC-14-drain-node/drain-node
    - ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/4-chaos/UC-14-drain-node/drain-node

Node-Evict:
  extends: .chaos_test_template
  script: 
    - chmod 775 ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/4-chaos/UC-15-evict-node/evict-node
    - ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/4-chaos/UC-15-evict-node/evict-node

Openebs-cleanup:
  image: openebs/openshift-ci:latest
  stage: CLEANUP
  script:
    - chmod 775 ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/5-cleanup/openebs-cleanup/openebs-delete.sh
    - ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/5-cleanup/openebs-cleanup/openebs-delete.sh
  
OS-cleanup:
  image: openebs/openshift-ci:latest
  stage: CLEANUP
  script:
    - chmod 775 ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/5-cleanup/OS-3.10-cleanup/OS-cleanup
    - ./Openshift-EE-3-10/pipelines/OpenEBS-base/stages/5-cleanup/OS-3.10-cleanup/OS-cleanup
